# Site settings
title: Flic & Steve Get Married!
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
    We're getting married - Come and join us! Assuming you're invited that is.
    If you don't know who we are, you're probably not invited. Sorry. Also, it's a bit odd
    that you found this really.
baseurl: "http://wedding.carlysle-davies.uk/" # the subpath of your site, e.g. /blog/
permalink: :title
exclude:
    - Gemfile.lock
    - rakefile.rb
    - deploy

# Build settings
markdown: kramdown
sass_dir: _compass/
gems:
  - jekyll-compass

defaults:
  - scope:
      path: ""
    values:
      layout: default
